import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import { Roboto } from "next/font/google";
const inter = Roboto({ subsets: ["latin"], weight: '500' });

export const metadata: Metadata = {
  title: "Tuff-Mail",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} antialiased bg-default-400/20`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
